import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
df = pd.read_csv("Titanic-Dataset.csv")
print("🔹 Original Data (First 5 rows):")
print(df.head())
print("\n🔹 Dataset Shape:", df.shape)
print("\n🔹 Missing Values:")
print(df.isnull().sum())
df.fillna(df.median(numeric_only=True), inplace=True)
le = LabelEncoder()
for col in df.select_dtypes(include='object').columns:
    df[col] = le.fit_transform(df[col].astype(str))
print("\n🔹 After Encoding:")
print(df.head())
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)
df = pd.DataFrame(df_scaled, columns=df.columns)
print("\n🔹 Preprocessed Data (First 5 rows):")
print(df.head())
print("\n🔹 Final Shape:", df.shape)
print("\n✅ Task Completed Successfully!")
